# This file was generated by GoReleaser. DO NOT EDIT.
class Wsgnatsd < Formula
  desc "A websocket server proxy for nats-server"
  homepage "https://github.com/aricart/wsgnatsd"
  version "0.8.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aricart/wsgnatsd/releases/download/v0.8.10/wsgnatsd-v0.8.10-darwin-amd64.zip"
    sha256 "38a1e1242a6a429a92849333956244edd53123e05e8461171a3900b3b1a2bb23"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aricart/wsgnatsd/releases/download/v0.8.10/wsgnatsd-v0.8.10-darwin-amd64.zip"
      sha256 "d758aa5ff8903b0c25cf267c16697810ccb7ec769a8b658f62e0019e7f035943"
    end
  end

  def install
    bin.install "wsgnatsd"
  end

  test do
    system "#{bin}/wsgnatsd --help"
  end
end
