# This file was generated by GoReleaser. DO NOT EDIT.
class Wsgnatsd < Formula
  desc "A websocket server proxy for nats-server"
  homepage "https://github.com/aricart/wsgnatsd"
  version "0.8.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aricart/wsgnatsd/releases/download/v0.8.6/wsgnatsd-darwin-amd64.zip"
    sha256 "16c9a7a4970e1e066e07dfddb862a4830880deb352f5b59a05fcb3388a48e367"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aricart/wsgnatsd/releases/download/v0.8.6/wsgnatsd-darwin-amd64.zip"
      sha256 "8e107bb96778fabf78e214d53b504fa6c8e03a64484ad2281fa946f05d7cd7b3"
    end
  end

  def install
    bin.install "program"
  end

  test do
    system "#{bin}/wsgnatsd --help"
  end
end
